{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Vectors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[0, 2, 4]"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# sum of two vectors\n",
    "def addn(v,w): return [v[i]+w[i] for i in range(len(w))]\n",
    "addn([0,1,2], [0,1,2])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[0, 2]"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# product of alpha and a vector\n",
    "def scalar_vector_mult(alpha, v): return [alpha*v[i] for i in range(len(v))]\n",
    "scalar_vector_mult(2,[0,1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "d:\\code\\sandbox\n"
     ]
    }
   ],
   "source": [
    "%cd ..\n",
    "from plotting import plot\n",
    "v = [3,2]\n",
    "plot([scalar_vector_mult(i/10, v) for i in range(-10, 11)], 5) #symmetric"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "class Vec:\n",
    "    def __init__(self, labels, function):\n",
    "        self.D = labels    #set\n",
    "        self.f = function  #represented as dict\n",
    "        \n",
    "    def setitem(self, d, val):\n",
    "        f[d] = val\n",
    "    \n",
    "    def getitem(self, d): \n",
    "        return self.f[d] if d in self.f else 0.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.0\n",
      "1.0\n",
      "0.0\n"
     ]
    }
   ],
   "source": [
    "v = Vec({'A','B','C'},{'A':1.0})\n",
    "for d in v.D:\n",
    "    if d in v.f:\n",
    "        print(v.f[d])\n",
    "\n",
    "print(v.getitem('A'))\n",
    "print(v.getitem('B'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'C', 'B'}\n"
     ]
    }
   ],
   "source": [
    "def no_mapping(v): return v.D-v.f.keys()\n",
    "D0 = no_mapping(v)\n",
    "print(D0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{0, 1} {}\n"
     ]
    }
   ],
   "source": [
    "# Zero-vector\n",
    "def zero_vec(D): return Vec(D,{})\n",
    "v0 = zero_vec({0,1})\n",
    "print(v0.D, v0.f)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Implementing full-fledged Vectors class"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 3, in test_vec\n",
      "Failed example:\n",
      "    from vec import Vec\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[0]>\", line 1, in <module>\n",
      "        from vec import Vec\n",
      "    ImportError: No module named 'vec'\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 10, in test_vec\n",
      "Failed example:\n",
      "    v = Vec({'a','b','c', 'd'},{'a':2,'c':1,'d':3})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[1]>\", line 1, in <module>\n",
      "        v = Vec({'a','b','c', 'd'},{'a':2,'c':1,'d':3})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 11, in test_vec\n",
      "Failed example:\n",
      "    v['d']\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[2]>\", line 1, in <module>\n",
      "        v['d']\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 13, in test_vec\n",
      "Failed example:\n",
      "    v['b']\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[3]>\", line 1, in <module>\n",
      "        v['b']\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 22, in test_vec\n",
      "Failed example:\n",
      "    v = Vec({'a', 'b', 'c'}, {'b':0})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[4]>\", line 1, in <module>\n",
      "        v = Vec({'a', 'b', 'c'}, {'b':0})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 23, in test_vec\n",
      "Failed example:\n",
      "    v['b'] = 5\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[5]>\", line 1, in <module>\n",
      "        v['b'] = 5\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 24, in test_vec\n",
      "Failed example:\n",
      "    v['b']\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[6]>\", line 1, in <module>\n",
      "        v['b']\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 26, in test_vec\n",
      "Failed example:\n",
      "    v['a'] = 1\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[7]>\", line 1, in <module>\n",
      "        v['a'] = 1\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 27, in test_vec\n",
      "Failed example:\n",
      "    v['a']\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[8]>\", line 1, in <module>\n",
      "        v['a']\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 35, in test_vec\n",
      "Failed example:\n",
      "    Vec({'a', 'b', 'c'}, {'a':0}) == Vec({'a', 'b', 'c'}, {'b':0})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[9]>\", line 1, in <module>\n",
      "        Vec({'a', 'b', 'c'}, {'a':0}) == Vec({'a', 'b', 'c'}, {'b':0})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 40, in test_vec\n",
      "Failed example:\n",
      "    Vec({'x','y','z'},{'y':1,'x':2}) == Vec({'x','y','z'},{'y':1,'z':0})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[10]>\", line 1, in <module>\n",
      "        Vec({'x','y','z'},{'y':1,'x':2}) == Vec({'x','y','z'},{'y':1,'z':0})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 42, in test_vec\n",
      "Failed example:\n",
      "    Vec({'a','b','c'}, {'a':0,'c':1}) == Vec({'a','b','c'}, {'a':0,'c':1,'b':4})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[11]>\", line 1, in <module>\n",
      "        Vec({'a','b','c'}, {'a':0,'c':1}) == Vec({'a','b','c'}, {'a':0,'c':1,'b':4})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 44, in test_vec\n",
      "Failed example:\n",
      "    Vec({'a','b','c'}, {'a':0,'c':1,'b':4}) == Vec({'a','b','c'}, {'a':0,'c':1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[12]>\", line 1, in <module>\n",
      "        Vec({'a','b','c'}, {'a':0,'c':1,'b':4}) == Vec({'a','b','c'}, {'a':0,'c':1})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 48, in test_vec\n",
      "Failed example:\n",
      "    Vec({'a','b'},{'a':1}) == Vec({'a','b'},{'b':1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[13]>\", line 1, in <module>\n",
      "        Vec({'a','b'},{'a':1}) == Vec({'a','b'},{'b':1})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 52, in test_vec\n",
      "Failed example:\n",
      "    Vec({'a','b'},{'a':1}) == Vec({'a','b'},{'a':2})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[14]>\", line 1, in <module>\n",
      "        Vec({'a','b'},{'a':1}) == Vec({'a','b'},{'a':2})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 60, in test_vec\n",
      "Failed example:\n",
      "    a = Vec({'a','e','i','o','u'}, {'a':0,'e':1,'i':2})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[15]>\", line 1, in <module>\n",
      "        a = Vec({'a','e','i','o','u'}, {'a':0,'e':1,'i':2})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 61, in test_vec\n",
      "Failed example:\n",
      "    b = Vec({'a','e','i','o','u'}, {'o':4,'u':7})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[16]>\", line 1, in <module>\n",
      "        b = Vec({'a','e','i','o','u'}, {'o':4,'u':7})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 62, in test_vec\n",
      "Failed example:\n",
      "    c = Vec({'a','e','i','o','u'}, {'a':0,'e':1,'i':2,'o':4,'u':7})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[17]>\", line 1, in <module>\n",
      "        c = Vec({'a','e','i','o','u'}, {'a':0,'e':1,'i':2,'o':4,'u':7})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 63, in test_vec\n",
      "Failed example:\n",
      "    a + b == c\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[18]>\", line 1, in <module>\n",
      "        a + b == c\n",
      "    NameError: name 'a' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 65, in test_vec\n",
      "Failed example:\n",
      "    d = Vec({'x','y','z'}, {'x':2,'y':1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[19]>\", line 1, in <module>\n",
      "        d = Vec({'x','y','z'}, {'x':2,'y':1})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 66, in test_vec\n",
      "Failed example:\n",
      "    e = Vec({'x','y','z'}, {'z':4,'y':-1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[20]>\", line 1, in <module>\n",
      "        e = Vec({'x','y','z'}, {'z':4,'y':-1})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 67, in test_vec\n",
      "Failed example:\n",
      "    f = Vec({'x','y','z'}, {'x':2,'y':0,'z':4})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[21]>\", line 1, in <module>\n",
      "        f = Vec({'x','y','z'}, {'x':2,'y':0,'z':4})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 68, in test_vec\n",
      "Failed example:\n",
      "    d + e == f\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[22]>\", line 1, in <module>\n",
      "        d + e == f\n",
      "    NameError: name 'd' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 70, in test_vec\n",
      "Failed example:\n",
      "    b + Vec({'a','e','i','o','u'}, {}) == b\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[23]>\", line 1, in <module>\n",
      "        b + Vec({'a','e','i','o','u'}, {}) == b\n",
      "    NameError: name 'b' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 77, in test_vec\n",
      "Failed example:\n",
      "    u1 = Vec({'a','b'}, {'a':1, 'b':2})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[24]>\", line 1, in <module>\n",
      "        u1 = Vec({'a','b'}, {'a':1, 'b':2})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 78, in test_vec\n",
      "Failed example:\n",
      "    u2 = Vec({'a','b'}, {'b':2, 'a':1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[25]>\", line 1, in <module>\n",
      "        u2 = Vec({'a','b'}, {'b':2, 'a':1})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 79, in test_vec\n",
      "Failed example:\n",
      "    u1*u2\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[26]>\", line 1, in <module>\n",
      "        u1*u2\n",
      "    NameError: name 'u1' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 81, in test_vec\n",
      "Failed example:\n",
      "    v1 = Vec({'p','q','r','s'}, {'p':2,'s':3,'q':-1,'r':0})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[27]>\", line 1, in <module>\n",
      "        v1 = Vec({'p','q','r','s'}, {'p':2,'s':3,'q':-1,'r':0})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 82, in test_vec\n",
      "Failed example:\n",
      "    v2 = Vec({'p','q','r','s'}, {'p':-2,'r':5})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[28]>\", line 1, in <module>\n",
      "        v2 = Vec({'p','q','r','s'}, {'p':-2,'r':5})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 83, in test_vec\n",
      "Failed example:\n",
      "    v1*v2\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[29]>\", line 1, in <module>\n",
      "        v1*v2\n",
      "    NameError: name 'v1' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 85, in test_vec\n",
      "Failed example:\n",
      "    w1 = Vec({'a','b','c'}, {'a':2,'b':3,'c':4})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[30]>\", line 1, in <module>\n",
      "        w1 = Vec({'a','b','c'}, {'a':2,'b':3,'c':4})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 86, in test_vec\n",
      "Failed example:\n",
      "    w2 = Vec({'a','b','c'}, {'a':12,'b':8,'c':6})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[31]>\", line 1, in <module>\n",
      "        w2 = Vec({'a','b','c'}, {'a':12,'b':8,'c':6})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 87, in test_vec\n",
      "Failed example:\n",
      "    w1*w2\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[32]>\", line 1, in <module>\n",
      "        w1*w2\n",
      "    NameError: name 'w1' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 92, in test_vec\n",
      "Failed example:\n",
      "    v1 = Vec({1, 2}, {1 : 3, 2 : 6})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[33]>\", line 1, in <module>\n",
      "        v1 = Vec({1, 2}, {1 : 3, 2 : 6})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 93, in test_vec\n",
      "Failed example:\n",
      "    v2 = Vec({1, 2}, {1 : 2, 2 : 1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[34]>\", line 1, in <module>\n",
      "        v2 = Vec({1, 2}, {1 : 2, 2 : 1})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 94, in test_vec\n",
      "Failed example:\n",
      "    v1 * v2\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[35]>\", line 1, in <module>\n",
      "        v1 * v2\n",
      "    NameError: name 'v1' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 101, in test_vec\n",
      "Failed example:\n",
      "    zero = Vec({'x','y','z','w'}, {})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[36]>\", line 1, in <module>\n",
      "        zero = Vec({'x','y','z','w'}, {})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 102, in test_vec\n",
      "Failed example:\n",
      "    u = Vec({'x','y','z','w'},{'x':1,'y':2,'z':3,'w':4})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[37]>\", line 1, in <module>\n",
      "        u = Vec({'x','y','z','w'},{'x':1,'y':2,'z':3,'w':4})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 103, in test_vec\n",
      "Failed example:\n",
      "    0*u == zero\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[38]>\", line 1, in <module>\n",
      "        0*u == zero\n",
      "    NameError: name 'u' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 105, in test_vec\n",
      "Failed example:\n",
      "    1*u == u\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[39]>\", line 1, in <module>\n",
      "        1*u == u\n",
      "    NameError: name 'u' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 107, in test_vec\n",
      "Failed example:\n",
      "    0.5*u == Vec({'x','y','z','w'},{'x':0.5,'y':1,'z':1.5,'w':2})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[40]>\", line 1, in <module>\n",
      "        0.5*u == Vec({'x','y','z','w'},{'x':0.5,'y':1,'z':1.5,'w':2})\n",
      "    NameError: name 'u' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 113, in test_vec\n",
      "Failed example:\n",
      "    zero = Vec({'x','y','z'}, {})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[41]>\", line 1, in <module>\n",
      "        zero = Vec({'x','y','z'}, {})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 114, in test_vec\n",
      "Failed example:\n",
      "    -zero == zero\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[42]>\", line 1, in <module>\n",
      "        -zero == zero\n",
      "    NameError: name 'zero' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 116, in test_vec\n",
      "Failed example:\n",
      "    v = Vec({0,1,2,3,4,'a'}, {0:1,1:-1,2:-1,3:1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[43]>\", line 1, in <module>\n",
      "        v = Vec({0,1,2,3,4,'a'}, {0:1,1:-1,2:-1,3:1})\n",
      "    NameError: name 'Vec' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 117, in test_vec\n",
      "Failed example:\n",
      "    -v == Vec({0,1,2,3,4,'a'}, {0:-1,1:1,2:1,3:-1})\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[44]>\", line 1, in <module>\n",
      "        -v == Vec({0,1,2,3,4,'a'}, {0:-1,1:1,2:1,3:-1})\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 119, in test_vec\n",
      "Failed example:\n",
      "    -(-v) == v\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[45]>\", line 1, in <module>\n",
      "        -(-v) == v\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "File \"..\\test_vec.py\", line 121, in test_vec\n",
      "Failed example:\n",
      "    v == -v\n",
      "Exception raised:\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Anaconda3\\lib\\doctest.py\", line 1320, in __run\n",
      "        compileflags, 1), test.globs)\n",
      "      File \"<doctest test_vec[46]>\", line 1, in <module>\n",
      "        v == -v\n",
      "    NameError: name 'v' is not defined\n",
      "**********************************************************************\n",
      "1 items had failures:\n",
      "  47 of  47 in test_vec\n",
      "***Test Failed*** 47 failures.\n"
     ]
    }
   ],
   "source": [
    "# Loading from custom path in Python 3.4+:\n",
    "# from importlib.util import *\n",
    "# spec = spec_from_file_location(\"vec\", \"vec_solution/vec.py\")\n",
    "# foo = module_from_spec(spec)\n",
    "# spec.loader.exec_module(foo)\n",
    "\n",
    "# Running all the unit-tests at once\n",
    "!python -m doctest ../test_vec.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "from vec import Vec\n",
    "v = Vec({'a','b','c', 'd'},{'a':2,'c':1,'d':3})\n",
    "# TODO: play with implemented code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
